# -*- coding: utf-8 -*-
"""__init__.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17fV9d-kGHBGw03d_523wY-qmWlM8Iyes
"""
#vazio
