# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15hL6Yr9aUwd_nG_l4DjRAfMas1fp6Pha
"""

!pip install --upgrade pip setuptools
from setuptools import setup

setup(
    name='pacote_aed',
    version='0.1',
    packages=['minhas_funcoes'],
    install_requires=[
        "numpy", "pandas", "seaborn", "statsmodels"
    ],
)
